### ISSUE TITLE
Update for kad@1.1.0-beta

### ISSUE THREAD

**Issue by gordonwritescode** [omphalos/kad-webrtc#1]
Kad has a new transport adapter interface. It is a very minor change in how the constructor is called. 

I'm happy to issue a PR this weekend. 

Cheers!

**Comment by omphalos** [comment]
@gordonwritescode That would be great, thanks.  In case something comes up and you're not able to I'll have a chance next weekend to take care of this.

Looking at the code, I assume the change is just breaking the `contact` info out of the `options` argument, right?

**Comment by gordonwritescode** [comment]
Yeah, instead of passing `Node` a constructor and having it initialize the transport with the options passed to the `Node`, now you create the transport instance yourself, giving it `(contact, options)` and pass the instance in. 

Ultimately, yeah I think it's as simple as adding the additional argument, the other stuff has been updated at the `RPC` parent class.

**Comment by gordonwritescode** [comment]
https://github.com/gordonwritescode/kad/blob/master/doc/rpc.md

**Comment by omphalos** [comment]
It's my understanding that this is closed by your latest PR.

**Comment by gordonwritescode** [comment]
:thumbsup:
