### ISSUE TITLE
Failed to build examples. 

### ISSUE THREAD

**Issue by zanetu** [omphalos/kad-webrtc#4]
```
$ npm run build-examples
npm ERR! Linux 3.14-2-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "build-examples"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.9

npm ERR! missing script: build-examples
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zanetu/download/node_modules/kad-webrtc/examples/npm-debug.log
```

**Comment by gordonwritescode** [comment]
Oops! I forgot to include the NPM scripts for building examples when breaking this out of kad core.

**Comment by omphalos** [comment]
@gordonwritescode I'll fix this.

**Comment by gordonwritescode** [comment]
@omphalos :thumbsup:

**Comment by omphalos** [comment]
@zanetu Thanks for reporting this issue!  This should be fixed now.  In case you run into any other problems, please speak up.  Thanks again!

**Comment by zanetu** [comment]
[**@omphalos**](https://github.com/omphalos) commented on [Dec 26, 2015, 10:08 AM EST](https://github.com/omphalos/kad-webrtc/issues/4#issuecomment-167330810 "2015-12-26T15:08:45Z - Replied by Github Comment Enhancer"):
> [@zanetu](https://github.com/zanetu) Thanks for reporting this issue!  This should be fixed now.  In case you run into any other problems, please speak up.  Thanks again!

Fix verified. Thanks.
